openapi: 3.0.0
info:
  title: Registration
  version: '1.0'
  description: Retrieve or update grazing registrations for authenticated user.
  contact:
    name: x
    url: x
    email: x@x.x
  termsOfService: x
  license:
    name: x
    url: x
servers: []
paths:
  /grazing/days:
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  days:
                    $ref: ./models/days.v1.json
      parameters:
        - schema:
            type: string
          in: query
          name: dateMin
          description: Date range filter
        - schema:
            type: string
          in: query
          name: dateMax
          description: Date range filter
      description: Retrieve a list of registration days.
    parameters: []
    post:
      summary: ''
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/days.v1.json
      description: Submit a list of registration day mutations or additions.
  /grazing/status:
    get:
      summary: null
      tags: []
      responses: {}
      description: Retrieve status details for registration
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/meta.v1.json
      parameters: []
    parameters: []
components:
  schemas: {}
  securitySchemes:
    FC-Access-Token:
      type: apiKey
      in: header
      description: ''
      name: Access token
    FC-API-Key:
      type: apiKey
      in: header
      name: API key
    FC-Member-Number:
      name: Member number
      type: apiKey
      in: header
    companyNumber:
      name: Company number
      type: apiKey
      in: query
